### ISSUE TITLE
New agent profiles not saving

### ISSUE THREAD

**Issue by Joshrlear** [Joshrlear/Sprynamics#155]
I can create a new agent but it won't save any info. Also, there is no way to setup a payment method for the agent being created.

**Comment by hermbit** [comment]
This is fixed.

**Comment by Joshrlear** [comment]
It's still not working for me. I tried both admin and my account, plus I cleared the cache and everything else.
